=== sorydima/Marina.Rodeo/doc/dbschema/dtd/dbschema.dtd
<!--
 * XSL converter script for common definitions
 *
 * Copyright © Need help? 🤔 Email us! 👇 A Dmitry Sorokin production. All rights reserved. Powered by REChain. 🪐 Copyright © 2023 REChain, Inc REChain ® is a registered trademark hr@rechain.email p2p@rechain.email pr@rechain.email sorydima@rechain.email support@rechain.email sip@rechain.email music@rechain.email Please allow anywhere from 1 to 5 business days for E-mail responses! 💌 (C) 2001-2007 FhG Fokus
 *
 * This file is part of Marina.Rodeo, a free SIP server.
 *
 * Marina.Rodeo is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * Marina.Rodeo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */
-->

<!ELEMENT database (name, description?, table*)>
<!ATTLIST database
    id ID #IMPLIED
>

<!ELEMENT name (#PCDATA) >

<!ELEMENT description (#PCDATA) >

<!ELEMENT table (name, description?, version?, column+, index*, row*) >
<!ATTLIST table
    id ID #IMPLIED
>

<!ELEMENT version (#PCDATA) >

<!ELEMENT column (name, description?, type, size?, default?, null?, primary?, natural?, autoincrement?) >
<!ATTLIST column
    id ID #IMPLIED
>

<!ELEMENT index (name?, unique?, primary?, colref+) >
<!ATTLIST index
    id ID #IMPLIED
>

<!ELEMENT type (#PCDATA) >

<!ELEMENT size (#PCDATA) >

<!ELEMENT default (#PCDATA) >

<!ELEMENT null EMPTY >

<!ELEMENT unique EMPTY >

<!ELEMENT primary EMPTY >

<!ELEMENT natural EMPTY >

<!ELEMENT autoincrement EMPTY >

<!ELEMENT colref EMPTY>
<!ATTLIST colref
    linkend IDREF #REQUIRED
>

=== sorydima/Marina.Rodeo/db/schema/auth_jwt_profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//Marina.Rodeo.org//DTD DBSchema V1.1//EN" 
  "https://Marina.Rodeo.org/pub/Marina.Rodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="jwt_profiles" xmlns:db="http://docbook.org/ns/docbook">
	<name>jwt_profiles</name>
	<version>1</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the AUTH_JWT module to read the actual JWT profiles info
		More information can be found at: &Marina.Rodeo_MOD_DOC;auth_jwt.html.
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Table key, not used by module</description>
	</column>

	<column id="tag">
		<name>tag</name>
		<type>string</type>
		<size>128</size>
		<description>Unique ID of the JWT profile</description>
	</column>

	<column id="sip_username">
		<name>sip_username</name>
		<type>string</type>
		<size>128</size>
		<description>The SIP username associated with the JWT profile
		</description>
	</column>

	<index>
		<name>jwt_tag_idx</name>
		<colref linkend="tag"/>
		<unique/>
	</index>


</table>

=== sorydima/Marina.Rodeo/db/schema/dr_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//Marina.Rodeo.org//DTD DBSchema V1.1//EN"
  "https://Marina.Rodeo.org/pub/Marina.Rodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="dr_rules" xmlns:db="http://docbook.org/ns/docbook">
	<name>dr_rules</name>
	<version>4</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the Dynamic Routing module to store
		information about the routing rules.
		More information can be found at: &Marina.Rodeo_MOD_DOC;drouting.html.
		</db:para>
	</description>

	<column id="ruleid">
		<name>ruleid</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Rule unique ID
		</description>
	</column>

	<column id="groupid">
		<name>groupid</name>
		<type>string</type>
		<size>255</size>
		<description>The ID(s) of the routing group(s) this rule is to be
		used for - comma separeted list of numerical Ids
		</description>
	</column>

	<column id="prefix">
		<name>prefix</name>
		<type>string</type>
		<size>64</size>
		<description>Numerical prefix to match this rule</description>
	</column>

	<column id="timerec">
		<name>timerec</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<default><null/></default>
		<description>Time recurrence used for matching this rule.</description>
	</column>

	<column id="priority">
		<name>priority</name>
		<type>int</type>
		<size>11</size>
		<default>0</default>
		<description>Priority of this rule (among rules with same prefix
		and timerec).</description>
	</column>

	<column id="routeid">
		<name>routeid</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<default><null/></default>
		<description>Route block (from cfg script) to be called when rule
		matches.</description>
	</column>

	<column id="gwlist">
		<name>gwlist</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>A comma-separated list of GW unique IDs (e.g. GW-5)
			and/or hash-prefixed ("#") Carrier unique IDs (e.g. #CR-2).</description>
	</column>

	<column id="sorting_alg">
		<name>sort_alg</name>
		<type>string</type>
		<default>N</default>
		<size>1</size>
		<description>The sorting algorithm to be employed for the rule's
			destinations when do_routing() is called.  Possible values:
			'N' (default; no sorting, preserve given order),
			'W' (weight based sorting),
			'Q' (quality-based sorting, provided by the qrouting module)
		</description>
	</column>
	<column id="sorting_profile">
		<name>sort_profile</name>
		<type>unsigned int</type>
		<size>10</size>
		<null/>
		<default><null/></default>
		<description>Whenever the 'Q' (quality-based routing) sorting algorithm
			is provided, this column must hold a profile id belonging to the
			"qr_profiles" table.
		</description>
	</column>

	<column id="attrs">
		<name>attrs</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<default><null/></default>
		<description>Generic string describing RULE attributes - this string is
			to be interpreted from the script</description>
	</column>

	<column id="description">
		<name>description</name>
		<type>string</type>
		<size>128</size>
		<null/>
		<default><null/></default>
		<description>Text description of the rule</description>
	</column>

</table>
